name: Sugerir uma melhoria
description: Proponha uma melhoria de uso ou compatibilidade.
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema que a melhoria resolve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solução sugerida
    validations:
      required: true
